#!/bin/bash
# Submit an adapter-extraction run through autoexp by composing the env vars
# from a small built-in recipe registry.
#
# Usage:
#     scripts/crc/submit_extract.sh <recipe>
#
# Recipes:
#     qwen35_27b_v1          v1 EU-PMC LoRA (rank 64, alpha 128) on Qwen3.5-27B VLM
#     qwen35_27b_v2          v2 EvoLM-mix LoRA (rank 32, alpha 64) on Qwen3.5-27B VLM
#     qwen35_9b_v2           v2 LoRA on Qwen3.5-9B causal LM
#     llama31_8b_v2          v2 LoRA on Llama-3.1-8B causal LM
#
# Each recipe configures:
#     CHECKPOINT     Auto-detected to the highest-numbered checkpoint-* under
#                    the training output dir.
#     OUTPUT         <training output dir>/adapter
#     BASE_MODEL     HF id of the base model
#     LORA_R, LORA_ALPHA      As-trained values
#     BASE_PATH      "model.language_model" for VLM bases, "" for causal-LM bases.
set -eo pipefail

SUPRA_ROOT=/path/to/SupraBench
RECIPE=${1:?usage: submit_extract.sh <recipe>}
AUTOEXP=${AUTOEXP:-/path/to/AutoExp-src/.venv/bin/autoexp}

case "${RECIPE}" in
  qwen35_27b_v1)
    OUT_DIR="${SUPRA_ROOT}/outputs/cpt_qwen35_eupmc"
    BASE_MODEL="Qwen/Qwen3.5-27B"
    LORA_R=64; LORA_ALPHA=128
    BASE_PATH="model.language_model"
    ;;
  qwen35_27b_v2)
    OUT_DIR="${SUPRA_ROOT}/outputs/cpt_qwen35_supra_v2"
    BASE_MODEL="Qwen/Qwen3.5-27B"
    LORA_R=32; LORA_ALPHA=64
    BASE_PATH="model.language_model"
    ;;
  qwen35_9b_v2)
    OUT_DIR="${SUPRA_ROOT}/outputs/cpt_qwen35_9b_supra_v2"
    BASE_MODEL="Qwen/Qwen3.5-9B"
    LORA_R=32; LORA_ALPHA=64
    BASE_PATH=""
    ;;
  llama31_8b_v2)
    OUT_DIR="${SUPRA_ROOT}/outputs/cpt_llama31_8b_supra_v2"
    BASE_MODEL="meta-llama/Llama-3.1-8B"
    LORA_R=32; LORA_ALPHA=64
    BASE_PATH=""
    ;;
  *)
    echo "unknown recipe: ${RECIPE}" >&2
    echo "valid: qwen35_27b_v1 qwen35_27b_v2 qwen35_9b_v2 llama31_8b_v2" >&2
    exit 2
    ;;
esac

GEN_DIR=${SUPRA_ROOT}/scripts/crc/_generated
mkdir -p "${GEN_DIR}"
LAUNCHER=${GEN_DIR}/extract_adapter_${RECIPE}.sh

cat > "${LAUNCHER}" <<EOL
#!/bin/bash
# Auto-generated by scripts/crc/submit_extract.sh recipe=${RECIPE} on \$(date)
set -eo pipefail
cd ${SUPRA_ROOT}
CHECKPOINT=\$(ls -d ${OUT_DIR}/checkpoint-* 2>/dev/null | sort -V | tail -1)
[[ -n "\${CHECKPOINT}" ]] || { echo "no checkpoint under ${OUT_DIR}"; exit 1; }
export CHECKPOINT
export OUTPUT="${OUT_DIR}/adapter"
export BASE_MODEL="${BASE_MODEL}"
export LORA_R=${LORA_R}
export LORA_ALPHA=${LORA_ALPHA}
export BASE_PATH="${BASE_PATH}"
exec ${SUPRA_ROOT}/scripts/crc/extract_adapter.sh
EOL
chmod +x "${LAUNCHER}"

echo "[submit_extract] generated ${LAUNCHER}"
echo "[submit_extract] submitting via ${AUTOEXP} (1 GPU, name=extract_adapter_${RECIPE})"

"${AUTOEXP}" submit --gpus 1 --name "extract_adapter_${RECIPE}" --cwd "${SUPRA_ROOT}" "${LAUNCHER}"
